### PR TITLE
[5.3.x]add settings that DataSourceTransactionManager#setRollbackOnCommitFaillure=true in xml files what using DataSourceTransactionManager.

### PR DESCRIPTION
**Pull request by bturamatuyu**
Please review #555 .

### CODE REVIEW

**Comment by kazuki43zoo** [comment]
@bturamatuyu 

please resolve conflict and apply this change to the `webspherelp-db2` and `webspheretr-db2` profiles.

**Comment by kazuki43zoo** [comment]
@bturamatuyu 
Please resolve conflict.

**Comment by bturamatuyu** [comment]
@kazuki43zoo san
Resolved conflict and rebase has complete.

**Comment by kazuki43zoo** [comment]
@bturamatuyu 

Please apply to webspheretr-db2.

**Comment by bturamatuyu** [comment]
@kazuki43zoo 
Applied to webspheretr-db2.

**Comment by kazuki43zoo** [comment]
@bturamatuyu 

Please backport 5.2.x.

**Pull request merged**
