### PR TITLE
#266: Create README.md & CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by kazuki43zoo**
Please review #266 .

### CODE REVIEW

**Comment by ikeyat** [comment]
Need to follow a change in https://github.com/terasolunaorg/terasoluna-gfw/issues/386

**Comment by kazuki43zoo** [comment]
@ikeyat 

I've foxed your review comment.
Please review again.

**Comment by ikeyat** [comment]
@attarudes 
Please check English grammar and words. I've agreed with the contents.

**Comment by ikeyat** [comment]
@btundes 
Please check English grammar and words. I've agreed with the contents.

**Comment by ikeyat** [comment]
@btundes 
Thanks for your comments. 

@kazuki43zoo 
I'm going to modify similar  sentences in README.md other than this repos.

**Comment by kazuki43zoo** [comment]
@ikeyat 

I've fixed review comment. Please review again !

**Comment by ikeyat** [comment]
Please backport.

**Pull request merged**
