### PR TITLE
Add same-transaction test-case in sequencer.#407

### PR DESCRIPTION
**Pull request by btmiyashitasts**
Please review #407

### CODE REVIEW

**Comment by ikeyat** [comment]
- [ ] Please re-format java files you modified.

**Comment by ikeyat** [comment]
@btishiwatasns 
Please review. It looks existing code has not been modified. Please check they are enough or not.

**Comment by btmiyashitasts** [comment]
Please review #407

**Comment by ikeyat** [comment]
@btishiwatasns has reviewed.

**Comment by ikeyat** [comment]
Please backport

**Pull request merged**
